version: '3.3'

services:
  postgressql:
    image: postgres:latest
    container_name: postgressql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hacker_news
    networks:
      postgressql-net:
        ipv4_address: 172.18.0.3
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

networks:
  postgressql-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.1/16